#Display rank, dense rank and row number for rating
select *,
rank() over (order by rating desc) as 'Rank',
dense_rank() over (order by rating desc) as 'Dense_Rank',
row_number() over (order by rating desc) as 'Row_Number'
from restaurants;

#Display rank, dense rank and row number for rating based on their cities
select *,
rank() over (partition by city order by rating desc) as 'Rank',
dense_rank() over (partition by city order by rating desc) as 'Dense_Rank',
row_number() over (partition by city order by rating desc) as 'Row_Number'
from restaurants;

#Display rank, dense rank and row number for rating based on their cuisines
select *,
rank() over (partition by cuisine order by rating desc) as 'Rank',
dense_rank() over (partition by cuisine order by rating desc) as 'Dense_Rank',
row_number() over (partition by cuisine order by rating desc) as 'Row_Number'
from restaurants;

#Display rank, dense rank and row number for rating based on their cities and also create new column with Abohar-1, Abohar-2
select *,
rank() over (partition by city order by rating desc) as 'Rank',
dense_rank() over (partition by city order by rating desc) as 'Dense_Rank',
row_number() over (partition by city order by rating desc) as 'Row_Number',

concat(city,"-",rank() over (partition by city order by rating desc)) as 'City_Rank',
concat(city,"-",dense_rank() over (partition by city order by rating desc)) as 'City_Dense_Rank',
concat(city,"-",row_number() over (partition by city order by rating desc)) as 'Unique_ID'

from restaurants;

#Find top 5 restaurants of every city as per their revenue

select*, cost*rating_count as 'Revenue'
from(
select *,
row_number() over (partition by city order by cost*rating_count desc) as 'Rank'
from restaurants) t where t.Rank<=5;

#Find top 5 restaurants of every cuisine as per their revenue

select*, cost*rating_count as 'Revenue'
from(
select *,
row_number() over (partition by cuisine order by cost*rating_count desc) as 'Rank'
from restaurants) t where t.Rank<=5;

#List the top 5 cuisines based on the revenue generated by top 5 restaurants of every cuisine

select cuisine, sum(cost*rating_count) as 'Revenue'
from(
select *,
row_number() over (partition by cuisine order by cost*rating_count desc) as 'Rank'
from restaurants) t where t.Rank<=5
group by cuisine
order by Revenue desc limit 5;











